// Code generated by "stringer -type=MetricKind"; DO NOT EDIT.

package collector

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Counter-1]
	_ = x[Gauge-2]
}

const _MetricKind_name = "UndefinedCounterGauge"

var _MetricKind_index = [...]uint8{0, 9, 16, 21}

func (i MetricKind) String() string {
	if i < 0 || i >= MetricKind(len(_MetricKind_index)-1) {
		return "MetricKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetricKind_name[_MetricKind_index[i]:_MetricKind_index[i+1]]
}
