{
 "title": "Visus",
 "time": { "from": "2022-10-31T19:45:16.385Z", "to": "2022-10-31T20:38:52.628Z" },
 "panels": [
  {
   "title": "QPS per statement",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "\nsum(rate(sqlactivity_exec_count[$__rate_interval])) by (statement)\n"
    }
   ]
  },
  {
   "title": "% Runtime",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\nsum by (cluster, statement,db_console) (sqlactivity_run_lat *rate(sqlactivity_exec_count[$__rate_interval])  / on () group_left sum(sqlactivity_run_lat * rate(sqlactivity_exec_count[$__rate_interval])) * 100)\n\n"
    }
   ]
  },
  {
   "title": "SQL Efficiency - Rows per type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(sqlefficiency_healtylio[$__rate_interval])) by  (cluster,type) ",
     "legendFormat": "Healthy Queries"
    },
    {
     "expr": "sum(rate(sqlefficiency_explicitlio[$__rate_interval])) by  (cluster,type) ",
     "legendFormat": "Explicit Queries"
    },
    {
     "expr": "sum(rate(sqlefficiency_fulllio[$__rate_interval])) by  (cluster,type) ",
     "legendFormat": "Queries with Full Scans"
    },
    {
     "expr": "sum(rate(sqlefficiency_ijoinlio[$__rate_interval])) by  (cluster,type) ",
     "legendFormat": "Queries with Index Joins"
    }
   ]
  },
  {
   "title": "Contended Tables",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "max(increase(contended_tables_num_events[$__rate_interval])) by  (cluster,table_name) "
    }
   ]
  },
  {
   "title": "Intents per table",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max(increase(intent_count[$__rate_interval])) by  (cluster,table_name) "
    }
   ]
  },
  {
   "title": "Blocking Statements",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 28 },
   "targets": [
    {
     "expr": "max(increase(blocking_statements_count[$__rate_interval])) by  (cluster,statement_id) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}