# Copyright 2024 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Tests
permissions: read-all
on:
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
  workflow_dispatch: # Allow manual runs to kick off benchmarks
    inputs:
      run_bench:
        description: Run benchmarks
        required: false
        type: boolean

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Copyright headers
        run: go run github.com/google/addlicense -c "The Cockroach Authors" -l apache -s -v  -check  -ignore '**/testdata/**/*' .

      - name: crlfmt returns no deltas
        if: ${{ !cancelled() }}
        run: |
          DELTA=$(go run github.com/cockroachdb/crlfmt .)
          echo $DELTA
          test -z "$DELTA"

      - name: Lint
        if: ${{ !cancelled() }}
        run: go run golang.org/x/lint/golint -set_exit_status ./...

      - name: Static checks
        if: ${{ !cancelled() }}
        run: go run honnef.co/go/tools/cmd/staticcheck -checks all ./...

      - name: Go Vet
        if: ${{ !cancelled() }}
        run: go vet ./...

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      COVER_OUT: coverage.out
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Go Tests
        run: go test -v -race -coverpkg=./internal/... -covermode=atomic -coverprofile=${{ env.COVER_OUT }} ./...
